/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AAA } from "../../app.controller";

/**
 * @controller AppController.getHello
 * @path POST /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHello(
    connection: IConnection,
    b: getHello.Input,
): Promise<getHello.Output> {
    return PlainFetcher.fetch(
        {
            ...connection,
            headers: {
                ...(connection.headers ?? {}),
                "Content-Type": "application/json",
            },
        },
        {
            ...getHello.METADATA,
            path: getHello.path(),
        } as const,
        b,
    );
}
export namespace getHello {
    export type Input = Primitive<AAA>;
    export type Output = Primitive<AAA>;

    export const METADATA = {
        method: "POST",
        path: "/",
        request: {
            type: "application/json",
            encrypted: false
        },
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/`;
    }
}