/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import type { IConnection, Primitive } from "@nestia/fetcher";
import type { AAA } from "../../app.controller";
/**
 * @controller AppController.getHello
 * @path POST /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getHello(connection: IConnection, b: getHello.Input): Promise<getHello.Output>;
export declare namespace getHello {
    type Input = Primitive<AAA>;
    type Output = Primitive<AAA>;
    const METADATA: {
        readonly method: "POST";
        readonly path: "/";
        readonly request: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly response: {
            readonly type: "application/json";
            readonly encrypted: false;
        };
        readonly status: null;
    };
    const path: () => string;
}
